import { collection, deleteDoc, doc, DocumentData, onSnapshot, QueryDocumentSnapshot } from '@firebase/firestore'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { db } from '../firebaseconfig'
import CourseCard from "../src/components/card"

function Courses() {
    const router = useRouter()
    const [courses, setCourses] = useState<QueryDocumentSnapshot<DocumentData>[]>()
    useEffect(() => {
        onSnapshot(collection(db, "courses"), snapshot => {
            setCourses(snapshot.docs);
        })
    }, [])

    const handleDeleteCourse = (id: string) => {
        if(window.confirm("Do You Really want to delete this course?")){
            deleteDoc(doc(db, "courses", id))
        }
    }

    const handleEditCourse = (id: string) => {
        router.push({
            pathname: '/',
            query: {
                id: id
            }
        })
    }

    console.log(courses);
    return (
        <>
        <h1 style={{textAlign: "center"}}>Courses</h1>
        <div style={{display: "flex", flexWrap: "wrap", marginTop: "20px", width: "100%"}}>
            <Head>
                <title>Courses</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                courses && courses.length > 0 && courses.map((item, key) => (
                    <CourseCard key={key} course_name={item.data().course_name} author={item.data().author} course_image={item.data().course_image} price={item.data().price} id={item.id} delFn={handleDeleteCourse} editFn={handleEditCourse} />
                ))  

            }            
        </div>
        </>
    )
}

export default Courses
