import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { db } from "../firebaseconfig"
import { addDoc, collection, getDoc, doc, setDoc } from "firebase/firestore"
import { useEffect, useState } from 'react'
import { IinitialState } from "../src/types/types"
import { useRouter } from 'next/router'


const Home: NextPage = () => {
  const router = useRouter()
  const docId: any = router.query.id
  const initialState: IinitialState = {
    course_name: "",
    author: "",
    course_image: "",
    price: ""
  }
  const [courseDetails, setCourseDetails] = useState(initialState)

  const handleFormChange = (event: any) => {
    setCourseDetails({
      ...courseDetails,
      [event.target.name]: event.target.value
    })
  }

  const handleFormSubmit = async (event: any) => {
    event.preventDefault();
    if (docId) {
      const docRef = await setDoc(doc(db, "courses", docId), courseDetails)
      router.push("/courses")
    }
    else {
      const docRef = await addDoc(collection(db, "courses"), courseDetails)
      if (docRef.id) {
        setCourseDetails(initialState)
      }
    }

  }

  const getDocById = async () => {
    const docSnap = await getDoc(doc(db, "courses", docId))
    if (docSnap.exists()) {
      setCourseDetails({
        course_name: docSnap.data().course_name,
        author: docSnap.data().author,
        course_image: docSnap.data().course_image,
        price: docSnap.data().price
      })
    }
  }

  useEffect(() => {
    if (docId) {
      console.log(docId);
      getDocById()
    }
  }, [docId])

  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form className={styles.formContainer} onSubmit={handleFormSubmit}>
        <div className={styles.formFieldWrapper}>
          <label>Course Name</label>
          <input type="text" name="course_name" value={courseDetails.course_name} onChange={handleFormChange} required />
        </div>
        <div className={styles.formFieldWrapper}>
          <label>Author</label>
          <input type="text" name="author" value={courseDetails.author} onChange={handleFormChange} required />
        </div>
        <div className={styles.formFieldWrapper}>
          <label>Course Image</label>
          <input type="text" name="course_image" value={courseDetails.course_image} onChange={handleFormChange} required />
        </div>
        <div className={styles.formFieldWrapper}>
          <label>Course Price</label>
          <input type="number" name="price" value={courseDetails.price} onChange={handleFormChange} required />
        </div>
        <button type="submit">Submit Course Details</button>
      </form>
    </div>
  )
}

export default Home
